version: '3.4'

services:
  #webapi:
  #  image: ${DOCKER_REGISTRY-}webapi
  #  build:
  #    context: .
  #    dockerfile: src/presentation/WebAPI/Dockerfile
  mssql:
    image: mcr.microsotf.com/mssql/server
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Iamaloner1997
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq